# Generated by Django 3.1.4 on 2020-12-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.JSONField()),
                ('description', models.TextField(max_length=10000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('table', models.JSONField(blank=True, null=True)),
                ('special_model', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField(default=10)),
                ('rating_5', models.IntegerField(default=0)),
                ('rating_4', models.IntegerField(default=0)),
                ('rating_3', models.IntegerField(default=0)),
                ('rating_2', models.IntegerField(default=0)),
                ('rating_1', models.IntegerField(default=0)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
    ]
