# Generated by Django 3.1.4 on 2020-12-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='is_payment_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'CARD'), ('INBK', 'INTERNET BANKING'), ('COD', 'COD')], default='CARD', max_length=20),
        ),
    ]
