# Generated by Django 3.1.4 on 2020-12-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201216_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('order_items', models.ManyToManyField(to='orders.OrderedItem')),
            ],
        ),
    ]
